#!/usr/bin/env python

import sys
sys.path.append('/SNS/users/19g/SEQUOIA/commissioning/python/analysis_tools')
from det_eff_corr import *

if len(sys.argv)<2:
       print "Usage det_eff_corr [filename]"
       sys.exit()

det_eff_corr(sys.argv[1],write_spe=True,debug=True)
