#!/bin/sh
#
#command="idb -gui -gdb -directory ../libclasses:../libcore:../bindings/matlab $*"
#
# DBX mode seems to work best
#
command="idb -gui -I ../libclasses:../libcore:../bindings/matlab $*"
echo $command
$command
