function ms_disp_or_slice;

% function ms_disp_or_slice;
% draw menu options for display or slice (conventional or PSD detectors) for single crystal samples

% === if Control Window non-existent, return
fig=findobj('Tag','ms_ControlWindow');
if isempty(fig),
   disp('Control Window non-existent. Return.')
   return;
end

% === if no analysis mode defined , return
obj=findobj(fig,'Tag','ms_analysis_mode');
if isempty(obj),
   disp('No analysis mode selected. Return.')
   return;
end

% === if Detector Type not defined, return
obj=findobj(fig,'Tag','ms_det_type');
if isempty(obj),
   disp('No detector type selected. Return.')
   return;
end

% === if no change to the type of detectors, return
psd=(get(obj,'Value')==1);
if psd&(~isempty(findobj(fig,'String','Slice plane'))),
   return;
elseif (~psd)&(~isempty(findobj(fig,'String','Display'))),
   return;
end
   
% === get position parameters for items displayed on the Control Window
pos=get(findobj(fig,'String','AnalysisMode'),'Position');
lineheight=pos(4);
oneline=[0 lineheight 0 0];
pos1=get(obj,'Position');
interlines=pos1(4)-lineheight;
white=get(obj,'BackgroundColor');
psd=(get(obj,'Value')==1); % =1 (PSD) =0 (conventional, non-PSD detectors)

% === find position of the 'Detector Trajectories' menu option
hend=findobj(fig,'String','Detector Trajectories');
if ~isempty(hend),
   ylow=get(hend,'Position');
   ylow=ylow(2)+ylow(4)/2;
end

% === delete display/slice and cut menu options referring to earlier detector settings
h=findobj(fig,'Type','uicontrol');
for i=1:length(h),
	cpos=get(h(i),'Position');
   if (cpos(2)<pos(2))&(isempty(hend)|cpos(2)>ylow),
     	delete(h(i));
     end
end        

% === update menu option for detector trajectories
if psd,
   strings={'Q_x','Q_y','Q_z','H','K','L','u1','u2','u3','Energy','|Q|','2Theta','Azimuth','Det Group Number'};
else
   strings={'Q_x','Q_y','Q_z','H','K','L','u1','u2','Energy','|Q|','2Theta','Azimuth','Det Group Number'};
end
set(findobj(fig,'Tag','ms_plot_traj_x'),'Value',2,'String',strings);
set(findobj(fig,'Tag','ms_plot_traj_y'),'Value',1,'String',strings);
strings{length(strings)+1}='none';
set(findobj(fig,'Tag','ms_plot_traj_z'),'String',strings,'Value',length(strings));
drawnow;

%========= Orthogonal Viewing Axes ==================
pos=pos-1.5*oneline;
h=uicontrol('Parent',fig,'Style','text','String','Orthogonal',...
   'Position',pos+[0 0 0*pos(3) 0],'BackgroundColor',white);
pos=pos-oneline;
h=uicontrol('Parent',fig,'Style','text','String','Viewing Axes',...
   'Position',pos+[0 0 0*pos(3) 0],'BackgroundColor',white);

%========= a* b* c* E ==================
%pos=pos-oneline;
h=uicontrol('Parent',fig,'Style','text','String','a*',...
	'HorizontalAlignment','center',...
   'Position',pos+[pos(3) 0 -pos(3)*1/3 0]);
h=uicontrol('Parent',fig,'Style','text','String','b*',...
	'HorizontalAlignment','center',...
   'Position',pos+[2*pos(3) 0 -pos(3)*1/3 0]);
h=uicontrol('Parent',fig,'Style','text','String','c*',...
	'HorizontalAlignment','center',...
   'Position',pos+[3*pos(3) 0 -pos(3)*1/3 0]);
h=uicontrol('Parent',fig,'Style','text','String','Energy',...
	'HorizontalAlignment','center',...
   'Position',pos+[4*pos(3) 0 -pos(3)*1/3 0]);
h=uicontrol('Parent',fig,'Style','text','String','Label',...
	'HorizontalAlignment','center',...
   'Position',pos+[5*pos(3) 0 0 0]);

%========= u1  ==================
pos=pos-oneline;
h=uicontrol('Parent',fig,'Style','text','String','u1',...
   'Position',pos);
h=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u11',...
   'Position',pos+[pos(3) 0 -pos(3)*1/3 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u12',...
   'Position',pos+[2*pos(3) 0 -pos(3)*1/3 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u13',...
   'Position',pos+[3*pos(3) 0 -pos(3)*1/3 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u14',...
   'Position',pos+[4*pos(3) 0 -pos(3)*1/3 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u1label',...
   'Position',pos+[5*pos(3) 0 0 interlines],...
   'HorizontalAlignment','left','Callback','ms_updatelabel(1)',...
   'BackgroundColor',white);

%========= u2  ==================
pos=pos-oneline;
h=uicontrol('Parent',fig,'Style','text','String','u2',...
   'Position',pos);
h=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u21',...
   'Position',pos+[pos(3) 0 -pos(3)*1/3 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u22',...
   'Position',pos+[2*pos(3) 0 -pos(3)*1/3 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u23',...
   'Position',pos+[3*pos(3) 0 -pos(3)*1/3 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u24',...
   'Position',pos+[4*pos(3) 0 -pos(3)*1/3 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u2label',...
   'Position',pos+[5*pos(3) 0 0 interlines],...
   'HorizontalAlignment','left','Callback','ms_updatelabel(2)',...
   'BackgroundColor',white);

if psd, % PSD detectors
%========= u3  ==================
	pos=pos-oneline;
	h=uicontrol('Parent',fig,'Style','text','String','u3',...
   	'Position',pos);
	h=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u31',...
   	'Position',pos+[pos(3) 0 -pos(3)*1/3 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white);
	h=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u32',...
  	 	'Position',pos+[2*pos(3) 0 -pos(3)*1/3 interlines],...
  	 	'HorizontalAlignment','left',...
  	 	'BackgroundColor',white);
	h=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u33',...
   	'Position',pos+[3*pos(3) 0 -pos(3)*1/3 interlines],...
	   'HorizontalAlignment','left',...
   	'BackgroundColor',white);
	h=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u34',...
  	 	'Position',pos+[4*pos(3) 0 -pos(3)*1/3 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white);
	h=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u3label',...
   	'Position',pos+[5*pos(3) 0 0 interlines],...
   	'HorizontalAlignment','left','Callback','ms_updatelabel(3)',...
   	'BackgroundColor',white);
end

%========= Calculate Projections ==================
%pos=pos-oneline;
h=uicontrol('Parent',fig,'Style','pushbutton','String','Calculate Projections',...
   'Callback','ms_calc_proj;',...
   'Position',pos+[6*pos(3) 0 pos(3) 0]); 

%========= Slice plane/Display  ==================
pos=pos-1.5*oneline;
if psd,
   h=uicontrol('Parent',fig,'Style','text','String','Slice plane',...
      'Position',pos,'BackgroundColor',white,'Tag','ms_slice_data');
   % === After each plot/surf slice, the slice_data will be stored in 'UserData' field of above object
else
   h=uicontrol('Parent',fig,'Style','text','String','Display',...
   	'Position',pos,'BackgroundColor',white);
end

%========= Slice plane, vz_min, vz_max ==================
if psd,	% PDS detectors
   pos=pos-oneline;
   h=uicontrol('Parent',fig,'Style','text','String','perp to axis',...
   	'Position',pos);
	h=uicontrol('Parent',fig,'Style','popupmenu','String',{'u1','u2','u3'},...
	   'Tag','ms_slice_z',...
  	 	'Position',pos+[pos(3) 0 pos(3)*1/4 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white,...
   	'Callback','ms_slice_axes;');
	h=uicontrol('Parent',fig,'Style','text','String','thickness ',...
  		'Position',pos+[2*pos(3)+pos(3)*1/4 0 -pos(3)*1/4 0]);
	h=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_slice_vz_min',...
   	'Position',pos+[3*pos(3) 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white);
	h=uicontrol('Parent',fig,'Style','text','String','to',...
  		'Position',pos+[4*pos(3) 0 0 0]);
	h=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_slice_vz_max',...
   	'Position',pos+[5*pos(3) 0 0 interlines],...
   	'HorizontalAlignment','left',...
      'BackgroundColor',white);
end

%========= Slice/Display vx_min, vx_max, bin_vx ==================
pos=pos-oneline;
if psd,
   h=uicontrol('Parent',fig,'Style','text','String','horizontal range ',...
		'Tag','ms_slice_x_axis',...
   	'Position',pos+[pos(3) 0 pos(3) 0]);
	h=uicontrol('Parent',fig,'Style','edit','Tag','ms_slice_vx_min',...
  	 	'Position',pos+[3*pos(3) 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white);
	h=uicontrol('Parent',fig,'Style','text','String','to',...
   	'Position',pos+[4*pos(3) 0 0 0]);
	h=uicontrol('Parent',fig,'Style','edit','Tag','ms_slice_vx_max',...
   	'Position',pos+[5*pos(3) 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white);
	h=uicontrol('Parent',fig,'Style','text','String','step',...
   	'Position',pos+[6*pos(3) 0 0 0]);
	h=uicontrol('Parent',fig,'Style','edit','Tag','ms_slice_bin_vx',...
   	'Position',pos+[7*pos(3) 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white);
else
   h=uicontrol('Parent',fig,'Style','text','String','horizontal range* ',...
		'Tag','ms_disp_x_axis',...
   	'Position',pos+[pos(3) 0 pos(3) 0]);
	h=uicontrol('Parent',fig,'Style','edit','Tag','ms_disp_vx_min',...
  	 	'Position',pos+[3*pos(3) 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white);
	h=uicontrol('Parent',fig,'Style','text','String','to *',...
   	'Position',pos+[4*pos(3) 0 0 0]);
	h=uicontrol('Parent',fig,'Style','edit','Tag','ms_disp_vx_max',...
   	'Position',pos+[5*pos(3) 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white);
end

%========= Slice/Display vy_min, vy_max, bin_vy ==================
pos=pos-oneline;
if psd,	% PDS detectors
	h=uicontrol('Parent',fig,'Style','text','String','vertical range',...
  		'Tag','ms_slice_y_axis',...
   	'Position',pos+[pos(3) 0 pos(3) 0]);
	h=uicontrol('Parent',fig,'Style','edit','Tag','ms_slice_vy_min',...
   	'Position',pos+[3*pos(3) 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white);
	h=uicontrol('Parent',fig,'Style','text','String','to',...
   	'Position',pos+[4*pos(3) 0 0 0]);
	h=uicontrol('Parent',fig,'Style','edit','Tag','ms_slice_vy_max',...
   	'Position',pos+[5*pos(3) 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white);
	h=uicontrol('Parent',fig,'Style','text','String','step',...
   	'Position',pos+[6*pos(3) 0 0 0]);
	h=uicontrol('Parent',fig,'Style','edit','Tag','ms_slice_bin_vy',...
   	'Position',pos+[7*pos(3) 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white);
else
   h=uicontrol('Parent',fig,'Style','text','String','vertical range* ',...
  		'Tag','ms_disp_y_axis',...
   	'Position',pos+[pos(3) 0 pos(3) 0]);
	h=uicontrol('Parent',fig,'Style','edit','Tag','ms_disp_vy_min',...
   	'Position',pos+[3*pos(3) 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white);
	h=uicontrol('Parent',fig,'Style','text','String','to *',...
   	'Position',pos+[4*pos(3) 0 0 0]);
	h=uicontrol('Parent',fig,'Style','edit','Tag','ms_disp_vy_max',...
   	'Position',pos+[5*pos(3) 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white);
end   
   
%========= Slice/Display Intensity range ==================
pos=pos-oneline;
if psd,
	h=uicontrol('Parent',fig,'Style','text','String','Intensity range*',...
   	'Position',pos+[pos(3) 0 pos(3) 0]);
	h=uicontrol('Parent',fig,'Style','edit','Tag','ms_slice_i_min',...
   	'Position',pos+[3*pos(3) 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white);
	h=uicontrol('Parent',fig,'Style','text','String','to *',...
   	'Position',pos+[4*pos(3) 0 0 0]);
	h=uicontrol('Parent',fig,'Style','edit','Tag','ms_slice_i_max',...
   	'Position',pos+[5*pos(3) 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white);
	h=uicontrol('Parent',fig,'Style','text','String','Colour map',...
   	'Position',pos+[6*pos(3) 0 0 0]);
	load coltab.dat -ascii;
	h=uicontrol('Parent',fig,'Style','popupmenu','Tag','ms_slice_colmap',...
   	'Position',pos+[7*pos(3) -interlines 0 interlines],...
   	'HorizontalAlignment','left',...
   	'String',{'black->red','log10(blk-red)','blue->red'},...
   	'BackgroundColor',white,'Value',1,'UserData',coltab);
else
   h=uicontrol('Parent',fig,'Style','text','String','Intensity range*',...
   	'Position',pos+[pos(3) 0 pos(3) 0]);
	h=uicontrol('Parent',fig,'Style','edit','Tag','ms_disp_i_min',...
   	'Position',pos+[3*pos(3) 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white);
	h=uicontrol('Parent',fig,'Style','text','String','to *',...
   	'Position',pos+[4*pos(3) 0 0 0]);
	h=uicontrol('Parent',fig,'Style','edit','Tag','ms_disp_i_max',...
   	'Position',pos+[5*pos(3) 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white);
	h=uicontrol('Parent',fig,'Style','text','String','Colour map',...
   	'Position',pos+[6*pos(3) 0 0 0]);
	load coltab.dat -ascii;
	h=uicontrol('Parent',fig,'Style','popupmenu','Tag','ms_disp_colmap',...
   	'Position',pos+[7*pos(3) -interlines 0 interlines],...
   	'HorizontalAlignment','left',...
   	'String',{'black->red','log10(blk-red)','blue->red'},...
   	'BackgroundColor',white,'Value',1,'UserData',coltab);
end
   
%========= Slice/Display Smooth Level and Shading ==================
pos=pos-oneline;
h=uicontrol('Parent',fig,'Style','text','String','Smoothing level*',...
   'Position',pos+[pos(3) 0 pos(3) 0]);
if psd,
	h=uicontrol('Parent',fig,'Style','edit','Tag','ms_slice_nsmooth',...
   	'Position',pos+[3*pos(3) 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white);
	h=uicontrol('Parent',fig,'Style','text','String','Shading',...
   	'Position',pos+[4*pos(3) 0 0 0]);
	h=uicontrol('Parent',fig,'Style','popupmenu','Tag','ms_slice_shad',...
   	'Position',pos+[5*pos(3) -interlines 0 interlines],...
   	'HorizontalAlignment','left',...
   	'String',{'flat','faceted','interp'},...
      'BackgroundColor',white,'Value',1);
else
	h=uicontrol('Parent',fig,'Style','edit','Tag','ms_disp_nsmooth',...
   	'Position',pos+[3*pos(3) 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white);
	h=uicontrol('Parent',fig,'Style','text','String','Shading',...
   	'Position',pos+[4*pos(3) 0 0 0]);
	h=uicontrol('Parent',fig,'Style','popupmenu','Tag','ms_disp_shad',...
   	'Position',pos+[5*pos(3) -interlines 0 interlines],...
   	'HorizontalAlignment','left',...
   	'String',{'flat','faceted'},...
      'BackgroundColor',white,'Value',1);
end   

%========= Do Slice and Do Surf Slice / Do Display ==================
%pos=pos-oneline;
if psd,
   h=uicontrol('Parent',fig,'Style','pushbutton','String','Plot Slice',...
   	'Callback','ms_slice;',...
   	'Position',pos+[6*pos(3) 0 0 0]); 
	h=uicontrol('Parent',fig,'Style','pushbutton','String','Surf Slice',...
   	'Callback','ms_slice(''surf'');',...
      'Position',pos+[7*pos(3) 0 0 0]);
else
   h=uicontrol('Parent',fig,'Style','pushbutton','String','Display',...
   	'Callback','ms_disp;',...
   	'Position',pos+[6*pos(3) 0 0 0]);    
end   

%========= Cut  ==================
pos=pos-1.5*oneline;
h=uicontrol('Parent',fig,'Style','text','String','Cut',...
   'Position',pos,'BackgroundColor',white);

%========= Cut axis, vx_min, vx_max ==================
pos=pos-oneline;
h=uicontrol('Parent',fig,'Style','text','String',' along axis ',...
   'Position',pos);
if psd,	% PDS detectors
	h=uicontrol('Parent',fig,'Style','popupmenu','String',{'u1','u2','u3'},...
	   'Tag','ms_cut_x',...
  		'Position',pos+[pos(3) 0 pos(3)*1/4 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white,...
      'Callback','ms_cut_axes;');
else
	h=uicontrol('Parent',fig,'Style','popupmenu','String',{'u1','u2'},...
	   'Tag','ms_cut_x',...
  		'Position',pos+[pos(3) 0 pos(3)*1/4 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white,...
      'Callback','ms_cut_axes;');
end
h=uicontrol('Parent',fig,'Style','text','String','from',...
   'Position',pos+[2*pos(3)+pos(3)*1/4 0 -pos(3)*1/4 0]);
h=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_cut_vx_min',...
   'Position',pos+[3*pos(3) 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','text','String','to',...
   'Position',pos+[4*pos(3) 0 0 0]);
h=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_cut_vx_max',...
   'Position',pos+[5*pos(3) 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','text','String','step',...
   'Position',pos+[6*pos(3) 0 0 0]);
h=uicontrol('Parent',fig,'Style','edit','Tag','ms_cut_bin_vx',...
   'Position',pos+[7*pos(3) 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white);

%========= Cut vy_min, vy_max ==================
pos=pos-oneline;
h=uicontrol('Parent',fig,'Style','text','String','thickness range',...
	'Tag','ms_cut_y_axis',...
   'Position',pos+[pos(3) 0 pos(3) 0]);
h=uicontrol('Parent',fig,'Style','edit','Tag','ms_cut_vy_min',...
   'Position',pos+[3*pos(3) 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','text','String','to',...
   'Position',pos+[4*pos(3) 0 0 0]);
h=uicontrol('Parent',fig,'Style','edit','Tag','ms_cut_vy_max',...
   'Position',pos+[5*pos(3) 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white);

%========= Cut vz_min, vz_max ==================
if psd,
	pos=pos-oneline;
	h=uicontrol('Parent',fig,'Style','text','String','thickness range',...
		'Tag','ms_cut_z_axis',...
   	'Position',pos+[pos(3) 0 pos(3) 0]);
	h=uicontrol('Parent',fig,'Style','edit','Tag','ms_cut_vz_min',...
   	'Position',pos+[3*pos(3) 0 0 interlines],...
   	'HorizontalAlignment','left',...
   	'BackgroundColor',white);
	h=uicontrol('Parent',fig,'Style','text','String','to',...
   	'Position',pos+[4*pos(3) 0 0 0]);
	h=uicontrol('Parent',fig,'Style','edit','Tag','ms_cut_vz_max',...
   	'Position',pos+[5*pos(3) 0 0 interlines],...
   	'HorizontalAlignment','left',...
      'BackgroundColor',white);
end

h=uicontrol('Parent',fig,'Style','text','String','Symbol',...
  	'Position',pos+[6*pos(3) 0 0 0]);
h=uicontrol('Parent',fig,'Style','popupmenu','Tag','ms_cut_symbol_colour',...
  	'Position',pos+[7*pos(3) 0 0 interlines],...
  	'String',{'white','red','blue','magenta','green','cyan','yellow','black'},...
  	'BackgroundColor',white);

%========= Cut Intensity range and Data Symbol ==================
pos=pos-oneline;
if psd,
   strings={'Intensity','Q_x','Q_y','Q_z','H','K','L','u1','u2','u3','Energy','|Q|','2Theta','Azimuth','Det Group Number'};
else
   strings={'Intensity','Q_x','Q_y','Q_z','H','K','L','u1','u2','Energy','|Q|','2Theta','Azimuth','Det Group Number'};
end
h=uicontrol('Parent',fig,'Style','popupmenu','String',strings,...
   'Value',1,'BackgroundColor',white,'Tag','ms_cut_intensity',...
   'Position',pos+[pos(3) 0 pos(3)*1/4 interlines]);
h=uicontrol('Parent',fig,'Style','text','String','range*',...
   'Position',pos+[(2+1/4)*pos(3) 0 -pos(3)*1/4 0]);
h=uicontrol('Parent',fig,'Style','edit','Tag','ms_cut_i_min',...
   'Position',pos+[3*pos(3) 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','text','String','to *',...
   'Position',pos+[4*pos(3) 0 0 0]);
h=uicontrol('Parent',fig,'Style','edit','Tag','ms_cut_i_max',...
   'Position',pos+[5*pos(3) 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','popupmenu','Tag','ms_cut_symbol_type',...
   'Position',pos+[6*pos(3) 0 0 interlines],...
   'String',{'circle o','square','diamond','pentagram','hexagram','star *','cross x','plus +',...
   'triangle u','triangle d','triangle r','triangle l','point .'},...
	'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','popupmenu','Tag','ms_cut_symbol_line',...
   'Position',pos+[7*pos(3) 0 0 interlines],...
   'String',{'no line','solid -','dashed --','dotted ..','dash-dot _.'},...
   'BackgroundColor',white);

%========= OutputFile + To Mfit pushbutton + Generate bkg(E) button ==================
pos=pos-oneline;
h=uicontrol('Parent',fig,'Style','text','String','OutputFile*',...
   'Position',pos+[0 0 0 0]);
h=uicontrol('Parent',fig,'Style','popupmenu','String',{'none','.cut','.xye','.smh','Mfit .cut','.hkl'},...
   'Value',1,'BackgroundColor',white,'Tag','ms_cut_OutputType',...
   'Position',pos+[1*pos(3) 0 pos(3)*1/4 interlines]);
h=uicontrol('Parent',fig,'Style','text','Tag','ms_cut_OutputDir',...
   'String',get(findobj('Tag','ms_DataDir'),'String'),...
   'Position',pos+[2*pos(3)+pos(3)*1/4 0 2*pos(3)-pos(3)*1/4 interlines],'Visible','off');
h=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_cut_OutputFile',...
   'Position',pos+[2*pos(3)+pos(3)*1/4 0 2*pos(3)-pos(3)*1/4 interlines],...
   'HorizontalAlignment','left',...
	'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','pushbutton','String','Browse',...
   'Callback','ms_pick_output',...
   'Position',pos+[5*pos(3) 0 0 0]);   
h=uicontrol('Parent',fig,'Style','pushbutton','String','To Mfit',...
   'Callback','ms_cut(''tomfit'');',...
   'Position',pos+[6*pos(3) 0 0 0]); 
h=uicontrol('Parent',fig,'Style','pushbutton',...
   'Tag','ms_bkg_E','String','Store bkg(E)',...
   'Callback','ms_cut(''store_bkg_E'');','UserData',[],...
   'Position',pos+[7*pos(3) 0 0 0],'Visible','on'); 

%========= Do Cut ==================
pos=pos-oneline;
h=uicontrol('Parent',fig,'Style','text','String','x-axis',...
   'Position',pos+[4*pos(3) 0 0 0]);
h=findobj(fig,'Tag','ms_cut_intensity');
if ~isempty(h),
   strings=get(h,'String');
   strings{1}='cut axis';
else
   strings{1}='cut axis';
end   
h=uicontrol('Parent',fig,'Style','popupmenu','Tag','ms_cut_xaxis',...
  	'Position',pos+[5*pos(3) -interlines/2 0 interlines],...
  	'String',strings,'Value',1,...
  	'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','pushbutton','String','Plot Cut',...
   'Callback','ms_cut;',...
   'Position',pos+[6*pos(3) 0 0 0]); 
h=uicontrol('Parent',fig,'Style','pushbutton','String','Plot Cut Over',...
   'Callback','ms_cut(''over'');',...
   'Position',pos+[7*pos(3) 0 0 0]); 

