function ms_powder_menu;

% function ms_powder_menu;
% draw menu options for powder mode

% === if Control Window non-existent, return
fig=findobj('Tag','ms_ControlWindow');
if isempty(fig),
   disp('Control Window non-existent. Return.')
   return;
end

% === return if not powder sample or not single crystal sample analysed in powder mode
sampobj=findobj(fig,'Tag','ms_sample');
if isempty(sampobj),
   disp('Could not identify sample type. Return.')
   return;
end
sample=get(sampobj,'Value');	% =1 if single crystal sample, = 2 if powder sample
if (sample==1),
	analobj=findobj(fig,'Tag','ms_analysis_mode');
	if isempty(analobj),
   	disp('Could not identify analysis mode for single crystal sample. Return.');
   	return;
   end
   analmode=get(analobj,'Value');	% =1 if single crystal sample in single crystal analysis mode,=2 if sc sample in powder mode
   if (analmode==1),
      disp('Single crystal sample in single crystal analysis mode. Cannot use functions in powder mode. Return.');
      return;
   end   
end

% === get position parameters for items displayed on the Control Window
pos=get(findobj(fig,'String','Sample'),'Position');
lineheight=pos(4);
oneline=[0 lineheight 0 0];
pos1=get(sampobj,'Position');
interlines=pos1(4)-lineheight;
if (sample==1)&(analmode==2),
   % single crystal sample analysed in powder mode delete viewing axes, slice/display and cut sections
   pos1=get(findobj(fig,'Style','text','String','Orthogonal'),'Position');
else % powder sample, delete Lattice parameters, viewing axes, slice/display and cut sections
   pos1=get(findobj(fig,'Style','text','String','Unit cell lattice parameters'),'Position');
end
white=get(sampobj,'BackgroundColor');

% === find position of the 'Detector Trajectories' menu option
hend=findobj(fig,'Style','text','String','Detector Trajectories');
if ~isempty(hend),
   ylow=get(hend,'Position');
   ylow=ylow(2)+ylow(4)/2;
end

% === delete Unit cell lattice parameters, Crystal Orientation, 
% === display/slice and cut menu options 
% === referring to single crystal settings
h=findobj(fig,'Type','uicontrol');
for i=1:length(h),
	cpos=get(h(i),'Position');
   if (cpos(2)<=pos1(2))&(isempty(hend)|cpos(2)>ylow),
     	delete(h(i));
   end
end  

if sample==2,	
	% === if sample is powder, delete (hkl) checkboxes, if present
	delete(findobj(fig,'type','uicontrol','Style','text','String','(hkl) points'));
	delete(findobj(fig,'type','uicontrol','style','checkbox','Tag','ms_plot_traj_hkl_points'));
	delete(findobj(fig,'type','uicontrol','style','text','String','(hkl) labels'));
	delete(findobj(fig,'type','uicontrol','style','checkbox','Tag','ms_plot_traj_hkl_labels'));
end

%========= Viewing Axes + Label ==================
pos=pos-11*oneline;
h=uicontrol('Parent',fig,'Style','text','String','Viewing Axes',...
   'Position',pos+[0 0 0*pos(3) 0],'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','text','String','Label',...
   'Position',pos+[2*pos(3) 0 0 0]);

%========= u1  ==================
pos=pos-oneline;
strings={'Energy','|Q|','2Theta','Azimuth','Det Group Number'};
h=uicontrol('Parent',fig,'Style','text','String','u1',...
   'Position',pos);
h=uicontrol('Parent',fig,'Style','popupmenu','Tag','ms_u1',...
   'Position',pos+[pos(3) 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'String',strings,'Value',2,...
   'Callback','ms_updatelabelu(1);');
h=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u1label',...
   'Position',pos+[2*pos(3) 0 0 interlines],...
   'HorizontalAlignment','left','Callback','ms_updatelabel(1)',...
   'BackgroundColor',white,'String','u1');

%========= u2  ==================
pos=pos-oneline;
h=uicontrol('Parent',fig,'Style','text','String','u2',...
   'Position',pos);
h=uicontrol('Parent',fig,'Style','popupmenu','Tag','ms_u2',...
   'Position',pos+[pos(3) 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white,'String',strings,'Value',1,...
	'Callback','ms_updatelabelu(2);');
h=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_u2label',...
   'Position',pos+[2*pos(3) 0 0 interlines],...
   'HorizontalAlignment','left','Callback','ms_updatelabel(2)',...
   'BackgroundColor',white,'String','u2');

%========= Calculate Projections ==================
pos=pos-oneline;
h=uicontrol('Parent',fig,'Style','pushbutton','String','Calculate Projections',...
   'Callback','ms_calc_proj;',...
   'Position',pos+[6*pos(3) 0 pos(3) 0]); 

%========= Slice plane/Display  ==================
pos=pos-1.5*oneline;
h=uicontrol('Parent',fig,'Style','text','String','Display',...
   'Position',pos,'BackgroundColor',white);

%========= Display vx_min, vx_max, bin_vx ==================
pos=pos-oneline;
h=uicontrol('Parent',fig,'Style','text','String','horizontal range ',...
	'Tag','ms_disp_x_axis',...
  	'Position',pos+[pos(3) 0 pos(3) 0]);
h=uicontrol('Parent',fig,'Style','edit','Tag','ms_disp_vx_min',...
 	'Position',pos+[3*pos(3) 0 0 interlines],...
  	'HorizontalAlignment','left',...
  	'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','text','String','to *',...
  	'Position',pos+[4*pos(3) 0 0 0]);
h=uicontrol('Parent',fig,'Style','edit','Tag','ms_disp_vx_max',...
  	'Position',pos+[5*pos(3) 0 0 interlines],...
  	'HorizontalAlignment','left',...
  	'BackgroundColor',white);

%========= Display vy_min, vy_max, bin_vy ==================
pos=pos-oneline;
h=uicontrol('Parent',fig,'Style','text','String','vertical range',...
	'Tag','ms_disp_y_axis',...
  	'Position',pos+[pos(3) 0 pos(3) 0]);
h=uicontrol('Parent',fig,'Style','edit','Tag','ms_disp_vy_min',...
  	'Position',pos+[3*pos(3) 0 0 interlines],...
  	'HorizontalAlignment','left',...
  	'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','text','String','to *',...
  	'Position',pos+[4*pos(3) 0 0 0]);
h=uicontrol('Parent',fig,'Style','edit','Tag','ms_disp_vy_max',...
  	'Position',pos+[5*pos(3) 0 0 interlines],...
  	'HorizontalAlignment','left',...
  	'BackgroundColor',white);
   
%========= Display Intensity range ==================
pos=pos-oneline;
h=uicontrol('Parent',fig,'Style','text','String','Intensity range*',...
  	'Position',pos+[pos(3) 0 pos(3) 0]);
h=uicontrol('Parent',fig,'Style','edit','Tag','ms_disp_i_min',...
  	'Position',pos+[3*pos(3) 0 0 interlines],...
  	'HorizontalAlignment','left',...
  	'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','text','String','to *',...
  	'Position',pos+[4*pos(3) 0 0 0]);
h=uicontrol('Parent',fig,'Style','edit','Tag','ms_disp_i_max',...
  	'Position',pos+[5*pos(3) 0 0 interlines],...
  	'HorizontalAlignment','left',...
  	'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','text','String','Colour map',...
  	'Position',pos+[6*pos(3) 0 0 0]);
load coltab.dat -ascii;
h=uicontrol('Parent',fig,'Style','popupmenu','Tag','ms_disp_colmap',...
  	'Position',pos+[7*pos(3) -interlines 0 interlines],...
  	'HorizontalAlignment','left',...
  	'String',{'black->red','log10(blk-red)','blue->red'},...
  	'BackgroundColor',white,'Value',1,'UserData',coltab);
   
%========= Display Smooth Level and Shading ==================
pos=pos-oneline;
h=uicontrol('Parent',fig,'Style','text','String','Smoothing level*',...
   'Position',pos+[pos(3) 0 pos(3) 0]);
h=uicontrol('Parent',fig,'Style','edit','Tag','ms_disp_nsmooth',...
  	'Position',pos+[3*pos(3) 0 0 interlines],...
  	'HorizontalAlignment','left',...
  	'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','text','String','Shading',...
  	'Position',pos+[4*pos(3) 0 0 0]);
h=uicontrol('Parent',fig,'Style','popupmenu','Tag','ms_disp_shad',...
  	'Position',pos+[5*pos(3) -interlines 0 interlines],...
  	'HorizontalAlignment','left',...
  	'String',{'flat','faceted'},...
   'BackgroundColor',white,'Value',1);

%========= Do Display ==================
%pos=pos-oneline;
h=uicontrol('Parent',fig,'Style','pushbutton','String','Display',...
  	'Callback','ms_disp;',...
  	'Position',pos+[6*pos(3) 0 0 0]);    

%========= Cut  ==================
pos=pos-1.5*oneline;
h=uicontrol('Parent',fig,'Style','text','String','Cut',...
   'Position',pos,'BackgroundColor',white);

%========= Cut axis, vx_min, vx_max ==================
pos=pos-oneline;
h=uicontrol('Parent',fig,'Style','text','String',' along axis ',...
   'Position',pos);
h=uicontrol('Parent',fig,'Style','popupmenu','String',{'u1','u2'},...
   'Tag','ms_cut_x',...
	'Position',pos+[pos(3) 0 pos(3)*1/4 interlines],...
  	'HorizontalAlignment','left',...
  	'BackgroundColor',white,...
   'Callback','ms_cut_axes;');
h=uicontrol('Parent',fig,'Style','text','String','from',...
   'Position',pos+[2*pos(3)+pos(3)*1/4 0 -pos(3)*1/4 0]);
h=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_cut_vx_min',...
   'Position',pos+[3*pos(3) 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','text','String','to',...
   'Position',pos+[4*pos(3) 0 0 0]);
h=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_cut_vx_max',...
   'Position',pos+[5*pos(3) 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','text','String','step',...
   'Position',pos+[6*pos(3) 0 0 0]);
h=uicontrol('Parent',fig,'Style','edit','Tag','ms_cut_bin_vx',...
   'Position',pos+[7*pos(3) 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white);

%========= Cut vy_min, vy_max ==================
pos=pos-oneline;
h=uicontrol('Parent',fig,'Style','text','String','thickness range',...
	'Tag','ms_cut_y_axis',...
   'Position',pos+[pos(3) 0 pos(3) 0]);
h=uicontrol('Parent',fig,'Style','edit','Tag','ms_cut_vy_min',...
   'Position',pos+[3*pos(3) 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','text','String','to',...
   'Position',pos+[4*pos(3) 0 0 0]);
h=uicontrol('Parent',fig,'Style','edit','Tag','ms_cut_vy_max',...
   'Position',pos+[5*pos(3) 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white);

h=uicontrol('Parent',fig,'Style','text','String','Symbol',...
  	'Position',pos+[6*pos(3) 0 0 0]);
h=uicontrol('Parent',fig,'Style','popupmenu','Tag','ms_cut_symbol_colour',...
  	'Position',pos+[7*pos(3) 0 0 interlines],...
  	'String',{'white','red','blue','magenta','green','cyan','yellow','black'},...
  	'BackgroundColor',white);

%========= Cut Intensity range and Data Symbol ==================
pos=pos-oneline;
strings={'Intensity','Energy','|Q|','2Theta','Azimuth','Det Group Number'};
if (sample==1),	% single crystal sample anlysed as powder
   strings={'Intensity','Q_x','Q_y','Q_z','H','K','L','Energy','|Q|','2Theta','Azimuth','Det Group Number'};
end
h=uicontrol('Parent',fig,'Style','popupmenu','String',strings,...
   'Value',1,'BackgroundColor',white,'Tag','ms_cut_intensity',...
   'Position',pos+[pos(3) 0 pos(3)*1/4 interlines]);
h=uicontrol('Parent',fig,'Style','text','String','range*',...
   'Position',pos+[(2+1/4)*pos(3) 0 -pos(3)*1/4 0]);
h=uicontrol('Parent',fig,'Style','edit','Tag','ms_cut_i_min',...
   'Position',pos+[3*pos(3) 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','text','String','to *',...
   'Position',pos+[4*pos(3) 0 0 0]);
h=uicontrol('Parent',fig,'Style','edit','Tag','ms_cut_i_max',...
   'Position',pos+[5*pos(3) 0 0 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','popupmenu','Tag','ms_cut_symbol_type',...
   'Position',pos+[6*pos(3) 0 0 interlines],...
   'String',{'circle o','square','diamond','pentagram','hexagram','star *','cross x','plus +',...
   'triangle u','triangle d','triangle r','triangle l','point .'},...
	'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','popupmenu','Tag','ms_cut_symbol_line',...
   'Position',pos+[7*pos(3) 0 0 interlines],...
   'String',{'no line','solid -','dashed --','dotted ..','dash-dot _.'},...
	'BackgroundColor',white);

%========= OutputFile + To Mfit pushbutton + Generate bkg(E) button ==================
strings={'none','.cut','.xye','.smh','Mfit .cut'};
if (sample==1), % single crystal sample analysed as powder
   strings={'none','.cut','.xye','.smh','Mfit .cut', '.hkl'};
end
pos=pos-oneline;
h=uicontrol('Parent',fig,'Style','text','String','OutputFile*',...
   'Position',pos+[0 0 0 0]);
h=uicontrol('Parent',fig,'Style','popupmenu','String',strings,...
   'Value',1,'BackgroundColor',white,'Tag','ms_cut_OutputType',...
   'Position',pos+[1*pos(3) 0 pos(3)*1/4 interlines]);
h=uicontrol('Parent',fig,'Style','text','Tag','ms_cut_OutputDir',...
   'String',get(findobj('Tag','ms_DataDir'),'String'),...
   'Position',pos+[2*pos(3)+pos(3)*1/4 0 2*pos(3)-pos(3)*1/4 interlines],'Visible','off');
h=uicontrol('Parent',fig,'Style','edit','Enable','on','Tag','ms_cut_OutputFile',...
   'Position',pos+[2*pos(3)+pos(3)*1/4 0 2*pos(3)-pos(3)*1/4 interlines],...
   'HorizontalAlignment','left',...
   'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','pushbutton','String','Browse',...
   'Callback','ms_pick_output',...
   'Position',pos+[5*pos(3) 0 0 0]);   
h=uicontrol('Parent',fig,'Style','pushbutton','String','To Mfit',...
   'Callback','ms_cut(''tomfit'');',...
   'Position',pos+[6*pos(3) 0 0 0]); 
h=uicontrol('Parent',fig,'Style','pushbutton',...
   'Tag','ms_bkg_E','String','Store bkg(E)',...
   'Callback','ms_cut(''store_bkg_E'');','UserData',[],...
   'Position',pos+[7*pos(3) 0 0 0],'Visible','on'); 

%========= Do Cut ==================
pos=pos-oneline;
h=uicontrol('Parent',fig,'Style','text','String','x-axis',...
   'Position',pos+[4*pos(3) 0 0 0]);
h=findobj(fig,'Tag','ms_cut_intensity');
if ~isempty(h),
   strings=get(h,'String');
   strings{1}='cut axis';
else
   strings{1}='cut axis';
end   
h=uicontrol('Parent',fig,'Style','popupmenu','Tag','ms_cut_xaxis',...
  	'Position',pos+[5*pos(3) -interlines/2 0 interlines],...
  	'String',strings,'Value',1,...
  	'BackgroundColor',white);
h=uicontrol('Parent',fig,'Style','pushbutton','String','Plot Cut',...
   'Callback','ms_cut;',...
   'Position',pos+[6*pos(3) 0 0 0]); 
h=uicontrol('Parent',fig,'Style','pushbutton','String','Plot Cut Over',...
   'Callback','ms_cut(''over'');',...
   'Position',pos+[7*pos(3) 0 0 0]); 